[build]
  command = "npm install && echo 'Skipping build for Express server'"
  publish = "public"  # Can be empty but must exist
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200